### PR TITLE
Set DOM element as min/maxPosition for dynamic drawer width

### PR DESCRIPTION
**Pull request by prud**
Adds the possibility to have a DOM element instead of a static number as minPosition / maxPosition to always use the current width when opening the drawer. This is crucial when the width of your navigation drawer can change, e.g. when having a bigger navigation on tablets.

usage:

```
var snapper = new Snap({
    element: document.getElementById('content'),
    maxPosition: document.getElementById('snap-drawer-left'),
    minPosition: document.getElementById('snap-drawer-right')
});
```

### CODE REVIEW

**Comment by jakiestfu** [comment]
Just a thought, you've changed a lot of code to allow for this. Why wouldn't you do something like set the min/maxPosition in the init method if an object is passed? That way no other code needs to change and there is only about two lines of code that'd need to be added for this logic. Thoughts?

**Comment by prud** [comment]
I tried to be as dynamic as possible with this in case the drawer width changes throughout the life-span of the Snap object. Valid cases are mobile devices after orientation changes or desktop usage when changing the viewport size.

**Comment by jakiestfu** [comment]
Do you think something like `snapper.refresh()` would serve a purpose then? it will fire all `init` methods (excluding binding of events)?

**Comment by prud** [comment]
I thought a bit more about the issue and came up with a solution that seems to work fine for now (without any snap.js code changes):

```
$(window).on('resize', function() {
    // refresh snapper with new drawer width
    snapper.settings({
        maxPosition: $('#myElement').width()
    });

    // refresh snapper position in case it's currently open
    if (isOpened) { snapper.open('left'); }
});
```

This will nicely refresh the drawer whether it's already opened or not.

You can close this request for now, I'll delete it later on.

**Pull request closed without merging**
