### PR TITLE
jshint valid and small fix

### PR DESCRIPTION
**Pull request by SimonWaldherr**

### CODE REVIEW

**Comment by SimonWaldherr** [comment]
that was fast ;-) thx

**Comment by jakiestfu** [comment]
Good fixes, thank you for taking the time, Simon!

I have a few questions if you don't mind answering them.
- Is the code legible to you, or is it confusing at any point?
- What could 'touchcancel' be used for?
- What do you feel could be better about this code to enhance adoption rate?

I was thinking about including more data-attributes like `data-snap-ignore`, maybe the following:
- `data-snap-toggle-left`
- `data-snap-toggle-right`
- `data-snap-open-left`
- `data-snap-open-right`
- `data-snap-close`

Also, I've been thinking about adding support for jQuery (for noobs), and possible building of additional styles for drawers, so at the end of the day, the user just needs to add the proper HTML. Thoughts?

**Comment by SimonWaldherr** [comment]
- the code is really great, more comments would be better, but it's good enough. 
- I connected the 'touchcancel' with the same code 'touchend' is used with, to prevent errors on special cases (e.g. notifications). I don't think it's necessary to make anything special in this cases.
- a better mobile demo (with qr code) for a fast test would be great. snap js Also the [inclusion in ratchet](https://github.com/maker/ratchet/issues/175) will bring more users ;-)

More data-attributes can't be wrong, but i like the clean code and don't think that jQuery will improve that.
That's for now, i will think about it and tell you more tomorrow.

**Comment by jakiestfu** [comment]
Thank you very much. I was thinking about just redirecting users to the mobile version if they're mobile so that way they don't have to think about it. Appreciate your feedback@

**Comment by SimonWaldherr** [comment]
you can combine both
- if a user comes on mobile, just redirect to the mobile demo
- else show a qr-code (on mobile projects i always search for a qr code to test it)

tomorrow i will play a little bit with snap.js and [PullToRefresh](https://github.com/SimonWaldherr/PullToRefresh), but i don't think, that there will be any incompatibilities.

**Comment by jasondavis** [comment]
sweet I was just thinking of playing with Snap.js and PullToRefresh,

**Pull request merged**
