### PR TITLE
Add support to install as web component

### PR DESCRIPTION
**Pull request by cayasso**

### CODE REVIEW

**Comment by jakiestfu** [comment]
Rad!

**Comment by cayasso** [comment]
Wow that was fast!! Thank you!

**Comment by jakiestfu** [comment]
Well thanks for contributing!

**Comment by cayasso** [comment]
FYI. I just added Snap.js to web components list https://github.com/component/component/wiki/Components#wiki-ui it should now show up under component.io or as soon as it refreshes.

Best,

JB

**Comment by jakiestfu** [comment]
@cayasso Hell yah man, thanks!

**Comment by lmartins** [comment]
@cayasso Could you provide some instructions on how to install it using component?

tried with:
             var Snap = require('jakiestfu/Snap.js');
            var snapper = new Snap({
              element: document.getElementById('content')
            });

but it always return:
     Uncaught Error: failed to require "jakiestfu/Snap.js" from "root"

**Comment by cayasso** [comment]
@lmartins In your component project do:

```
   $ component install jakiestfu/Snap.js
```

then you should be able to do form your index.js (or your js file):

```
   var Snap = require('Snap.js');
   var snapper = new Snap({...});
```

Notice that you have to use "Snap.js" instead of "jakiestfu/Snap.js".
Remember also to run `make` or `component build` in your project before trying require.

**Comment by lmartins** [comment]
For some reason I have to namespace components, for example, I must call component-tip and not only tip.
With this i've tried both approaches and with both I get the "failed to require" message.

I've already ran the commands you've mention.

Im gonna look further into this, if I come to any conclusion i'll post it here.

Thanks

**Comment by cayasso** [comment]
Are you trying in an actually component project file or just in a regular
js global file?

Check this component example structure
https://github.com/cayasso/pull-to-refresh

On Fri, May 10, 2013 at 1:55 PM, Luis Martins notifications@github.comwrote:

> For some reason I have to namespace components, for example, I must call
> component-tip and not only tip.
> With this i've tried both approaches and with both I get the "failed to
> require" message.
> 
> I've already ran the commands you've mention.
> 
> Im gonna look further into this, if I come to any conclusion i'll post it
> here.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jakiestfu/Snap.js/pull/27#issuecomment-17741058
> .

## 

J.B.

**Pull request merged**
