### PR TITLE
The simple housekeep

### PR DESCRIPTION
**Pull request by T145**
Hope this helps (a bit more :P)! :palm_tree:

### CODE REVIEW

**Comment by edwardsdl** [comment]
@T145 The original minified file is ~8.4 kb while this one is ~14.6 kb. Your version is almost 74% larger.

**Comment by jasondavis** [comment]
@T145 I think you fail to see what the `Minified` file is meant for.  It not not meant to be highly readable.  Notice how there is a `Snap.js` and a `Snap.min.js`...he didn't just get bored and make 2 versions for fun, one is minified as mentioned to increase performance by smaller file size to download.

**Comment by T145** [comment]
Ah ok. I'll make the necessary adjustment and push a commit :P

**Comment by jakiestfu** [comment]
@T145 I sincerely appreciate you taking the time to reorganize Snap.js, but for the time being, I am the main contributor, and I'd prefer the library to retain it's current formatting of syntax. I have and will continue to utilize some of the code patterns you have put forth in your version, thanks again

**Comment by T145** [comment]
No problem! If the indentation is really that big of a deal, I can always just alter it back w/ a different editor!

**Pull request closed without merging**
