### PR TITLE
Separated base/required styles from demo.css

### PR DESCRIPTION
**Pull request by justindarc**
Extracted base/required styles out from demo styles into separate CSS file. Simplified the base HTML markup for the base styles. This should simplify integration into external projects by keeping the demo styles (color theming) separate from the base/required styles (positioning).

### CODE REVIEW

**Comment by jakiestfu** [comment]
You're the man!

**Comment by justindarc** [comment]
Haha. Thanks! I have another fix I'll probably check in later today to prevent Mobile Safari from "bouncing" when you scroll when you're already at the extent of the scrolling area. By the way, THANK YOU for creating this awesome little library! I had to start a project about two weeks ago and was going to attempt to make something to do the sliding drawers, but then I found this. It worked perfectly for what I needed!

**Comment by jakiestfu** [comment]
@justindarc Bouncing, you mean the top/bottom elasticity when you're done scrolling? Dude, if you could prevent that, you'd be a god, that's be so awesome! I am adding legacy support for shit like IE right now so the codebase may change.

**Comment by justindarc** [comment]
Yep. That's exactly what I'm talking about. I have it working in the app I'm working on. I'll extract it out and send another PR later when I get back home.

**Comment by justindarc** [comment]
@jakiestfu Here's the code I'm using to prevent the elastic bouncing when you start scrolling past the extremities on iOS. I was gonna try and put it right into snap.js, but wasn't sure how you wanted to implement it:

``` javascript
if (!!('ontouchstart' in window)) {
    window.addEventListener('touchstart', function(evt) {
        var element = evt.target;

        while (element) {
            if (element.classList.contains('snap-drawer') ||
                element.classList.contains('snap-content')) {
                var scrollHeight = element.scrollHeight;
                var offsetHeight = element.offsetHeight;
                var scrollTop    = element.scrollTop;
                var maxScrollTop = scrollHeight - offsetHeight;

                if (scrollTop <= 0) element.scrollTop = 1;
                if (scrollTop >= maxScrollTop) element.scrollTop = maxScrollTop - 1;
                return;
            }

            else {
                element = element.parentNode;
            }
        }
    });
}
```

**Comment by justindarc** [comment]
Also, I should mention that the code above uses event delegation to attach itself which may be overkill if you aren't creating new drawers, etc. dynamically.

**Comment by jasondavis** [comment]
This will be a great addition!  Thanks for sharing

**Comment by jakiestfu** [comment]
@justindarc I used this code but I am afraid I saw no difference in any scrolling behaviors. Do you think you can make a small demo?

**Comment by justindarc** [comment]
@jakiestfu I'll try and throw a demo together today. When I was testing it on the default.html page, unfortunately since the main content area doesn't overflow, the elasticity can't be stopped. However, the drawer content _does_ overflow and it correctly prevented the elastic bounce (where the entire Mobile Safari toolbar and all bounces offscreen) inside those areas. I'm still investigating how to handle the case where there is not enough content to overflow and scroll (such as the main content area in the demos) and I have a few ideas that might work.

**Pull request merged**
