### PR TITLE
Now using bower.json, fixed #192

### LINKED ISSUE #192: Bower component.json deprecated
With Bower is using deprecated component.json file.

### PR DESCRIPTION
**Pull request by kennethkalmer**
Also updated the version here, and the `main` key to point to `dist/latest/snap.(js|css)` respectively

### CODE REVIEW

**Comment by kennethkalmer** [comment]
Wait wait, will have to redo this properly to support component.io & bower at the same time...

**Comment by chellem** [comment]
I can't download it from bower tho.  Is there a problem with the name?

**Comment by kennethkalmer** [comment]
`bower install --save kennethkalmer/snapjs#v2.0`

That should work, but the directory name will be `Snap.js`. Alternatively you could use `snapjs=kennethkalmer/snapjs#v2.0` to have it saved to `snapjs`.

**Comment by chellem** [comment]
perfect :+1:

**Comment by frankie-loves-jesus** [comment]
@kennethkalmer could you make sure it's available via http://bower.io/search/?q=snap? That way I can add it to https://rails-assets.org/components/new.

**Comment by frankie-loves-jesus** [comment]
@kennethkalmer I just regged `kennethkalmer-snapjs`. Hopefully it should be searchable via http://bower.io/ soon.

Tried adding it to https://rails-assets.org/components/new but getting `kennethkalmer-snapjs has no versions defined. Please create an issue in component's repository.` -- maybe you need to set a semver-compatible version ie. `2.0.0-rc.1`?

**Comment by kennethkalmer** [comment]
@frankie-loves-jesus thanks for the feedback, will clean this up a bit more

**Comment by frankie-loves-jesus** [comment]
Anytime @kennethkalmer. Looking forward to your update.

**Comment by frankie-loves-jesus** [comment]
@kennethkalmer any news? @jakiestfu we need you man!

**Comment by jakiestfu** [comment]
@frankie-loves-jesus @chellem @kennethkalmer Sorry, fellas. Here we go:

``` bash
$ bower info snapjs

...

Available versions:
  - 2.0.0-rc1
  - 1.9.3
```

**Comment by frankie-loves-jesus** [comment]
Yo! Welcome back! Thank you so much man, I really appreciate it.

**Comment by rvanbaalen** [comment]
I had to look up the bower install instructions in this thread so I've added it to the README as well now :+1:

**Pull request merged**
