### PR TITLE
Added new snap.js events: close, open, expandLeft, expandRight, enabled,...

### PR DESCRIPTION
**Pull request by jbest84**
... and disabled. Updated README to reflect this change.

Refs #91

### CODE REVIEW

**Comment by jbest84** [comment]
Our QA found an issue where changing the device orientation when the snap.js menu was open would cause the body css classes to remain even though the menu closed. Added a fix for this as well.

**Comment by leighton-tidwell** [comment]
So we just redowload the .js file and thats the updated version?

**Comment by jbest84** [comment]
Found the root cause of the issue (un-did my previous commit). utils.klass.remove no longer relies on ordering. The class name is removed, and the remaining string is trimmed.

**Comment by jbest84** [comment]
@kingofslowmo My pull request does not update the minified version. Our app uses the un-minified version (we have our own build process).

**Comment by leighton-tidwell** [comment]
I'm just using the file snap.js. If that has anything to do with what your talking about, @jbest84

**Comment by jbest84** [comment]
@kingofslowmo Sure - you are free to grab the changes if you want. Just keep in mind the owner if this project may or may not accept my pull request.

**Pull request merged**
